set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'Chiel92/vim-autoformat'


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line



set directory=$HOME/.vim/swap//
set backupdir=$HOME/.vim/backup//
map <F5> :w <CR> :!gfortran % -o %<.o && ./%<.o <CR>
map <F2> :Autoformat<CR>
highlight LineNr ctermfg=grey

let fortran_free_source=1
let fortran_do_enddo=1
filetype plugin indent on
syntax on

set nu
set ruler

set showcmd

set smarttab
set expandtab
set smartindent
set autoindent
set tabstop=2
set shiftwidth=2

set bs=2

set incsearch
set ignorecase
set smartcase

